import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {supabase} from "./supabase";
import "./styles.css";

const today=()=>new Date().toISOString().slice(0,10);
const score=a=>Math.min(30,Math.floor((a.steps||0)/10000*30))+(a.workout?30:0)+(a.food_target?20:0)+(a.water_target?10:0)+(a.sleep_target?10:0);
const invite=()=>Math.random().toString(36).slice(2,8).toUpperCase();

function Auth({msg}){const[m,setM]=useState("login"),[email,setE]=useState(""),[pass,setP]=useState("");
async function go(e){e.preventDefault();const r=m==="login"?await supabase.auth.signInWithPassword({email,password:pass}):await supabase.auth.signUp({email,password:pass});if(r.error)alert(r.error.message);else if(m==="signup")alert("Account created. Check your email if confirmation is enabled.");}
return <div className="center"><form className="card auth" onSubmit={go}><div className="logo">🏆</div><h1>Fitness Wars</h1><p>Turn healthy habits into a competition.</p><input placeholder="Email" type="email" value={email} onChange={e=>setE(e.target.value)} required/><input placeholder="Password" type="password" value={pass} onChange={e=>setP(e.target.value)} minLength="6" required/><button> {m==="login"?"Log in":"Create account"} </button><a onClick={()=>setM(m==="login"?"signup":"login")}>{m==="login"?"Create an account":"Log in instead"}</a>{msg&&<small>{msg}</small>}</form></div>}

function Setup({user,onReady}){const[name,setN]=useState(""),[cname,setC]=useState("Fitness Wars"),[code,setCode]=useState("");
async function profile(n){const r=await supabase.from("profiles").upsert({id:user.id,display_name:n},{onConflict:"id"});if(r.error)throw r.error}
async function create(){try{await profile(name);const r=await supabase.from("challenges").insert({name:cname,invite_code:invite(),created_by:user.id}).select().single();if(r.error)throw r.error;const j=await supabase.from("challenge_members").insert({challenge_id:r.data.id,user_id:user.id});if(j.error)throw j.error;localStorage.setItem("fw_challenge",r.data.id);onReady()}catch(e){alert(e.message)}}
async function join(){try{await profile(name);const r=await supabase.from("challenges").select("*").eq("invite_code",code.toUpperCase()).single();if(r.error)throw new Error("Challenge code not found");const j=await supabase.from("challenge_members").upsert({challenge_id:r.data.id,user_id:user.id},{onConflict:"challenge_id,user_id"});if(j.error)throw j.error;localStorage.setItem("fw_challenge",r.data.id);onReady()}catch(e){alert(e.message)}}
return <div className="center"><div className="card setup"><div className="logo">🏆</div><h1>Join Fitness Wars</h1><input placeholder="Your name" value={name} onChange={e=>setN(e.target.value)}/><hr/><h3>Create a challenge</h3><input value={cname} onChange={e=>setC(e.target.value)}/><button disabled={!name.trim()} onClick={create}>Create challenge</button><div className="or">OR</div><h3>Join with a code</h3><input placeholder="6-character code" value={code} onChange={e=>setCode(e.target.value)}/><button disabled={!name.trim()||code.length<4} onClick={join}>Join challenge</button></div></div>}

function App(){const[s,setS]=useState(null),[profile,setProfile]=useState(null),[challenge,setChallenge]=useState(null),[members,setMembers]=useState([]),[acts,setActs]=useState([]),[tab,setTab]=useState("board"),[msg,setMsg]=useState("");
async function load(user=s?.user){if(!user)return;const p=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();setProfile(p.data);const id=localStorage.getItem("fw_challenge");if(!id)return;const c=await supabase.from("challenges").select("*").eq("id",id).maybeSingle();if(!c.data)return;setChallenge(c.data);const m=await supabase.from("challenge_members").select("user_id,profiles:user_id(id,display_name)").eq("challenge_id",id);setMembers(m.data||[]);const a=await supabase.from("daily_activity").select("*").eq("challenge_id",id).eq("activity_date",today());setActs(a.data||[])}
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setS(data.session);if(data.session)load(data.session.user)});const x=supabase.auth.onAuthStateChange((_e,ss)=>{setS(ss);if(ss)load(ss.user)});return()=>x.data.subscription.unsubscribe()},[]);
const board=useMemo(()=>members.map(m=>{const a=acts.find(x=>x.user_id===m.user_id)||{};return{...m.profiles,points:score(a),steps:a.steps||0}}).sort((a,b)=>b.points-a.points),[members,acts]);
async function save(v){const r=await supabase.from("daily_activity").upsert({user_id:s.user.id,challenge_id:challenge.id,activity_date:today(),...v},{onConflict:"user_id,challenge_id,activity_date"});if(r.error)setMsg(r.error.message);else{setMsg("Saved!");load()}}
if(!s)return <Auth msg={msg}/>; if(!profile||!challenge)return <Setup user={s.user} onReady={()=>load()}/>;
const mine=acts.find(a=>a.user_id===s.user.id)||{steps:0,workout:false,food_target:false,water_target:false,sleep_target:false};
return <><header><b>🏆 Fitness Wars</b><button className="ghost" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><main><section className="hero"><div><small>TODAY</small><h1>{board.find(x=>x.id===s.user.id)?.points||0}<em>/100</em></h1><p>{challenge.name}</p></div><div className="invite">Invite code<br/><strong>{challenge.invite_code}</strong><button onClick={()=>navigator.clipboard?.writeText(challenge.invite_code)}>Copy</button></div></section><nav><button className={tab==="board"?"active":""} onClick={()=>setTab("board")}>🏆 Leaderboard</button><button className={tab==="track"?"active":""} onClick={()=>setTab("track")}>✍️ Track today</button></nav>{msg&&<div className="notice">{msg}</div>}{tab==="board"?<><h2>Today's leaderboard</h2><div className="board">{board.map((p,i)=><div className="row" key={p.id}><b>{["🥇","🥈","🥉"][i]||`#${i+1}`}</b><span className="avatar">{p.display_name?.[0]}</span><span><strong>{p.display_name}</strong><small>{p.steps.toLocaleString()} steps</small></span><i><u style={{width:p.points+"%"}}/></i><strong>{p.points}</strong></div>)}</div><h2>Scoring</h2><p>🚶 10k steps 30 pts · 🏋️ Workout 30 · 🥗 Food 20 · 💧 Water 10 · 😴 Sleep 10</p></>:<Tracker value={mine} onSave={save}/>}</main></>}

function Tracker({value,onSave}){const[v,setV]=useState(value);return <div className="card tracker"><h2>Track today</h2><label>Steps<input type="number" min="0" value={v.steps} onChange={e=>setV({...v,steps:+e.target.value})}/></label>{[["workout","🏋️ Workout completed","30"],["food_target","🥗 Hit my food target","20"],["water_target","💧 Hit my water target","10"],["sleep_target","😴 Hit my sleep target","10"]].map(x=><label className="check"><input type="checkbox" checked={v[x[0]]} onChange={e=>setV({...v,[x[0]]:e.target.checked})}/>{x[1]} <small>{x[2]} pts</small></label>)}<div className="preview">Today's score <b>{score(v)}/100</b></div><button onClick={()=>onSave(v)}>Save progress</button></div>}
createRoot(document.getElementById("root")).render(<App/>);